title = "Florian Franzen"
baseURL = "https://florian.franzen.io"
tags = ["portfolio", "web design", "blog"]
locale = "en-US"
config = "config.toml"
canonifyURLS = true
googleAnalytics = ""
disableKinds = ["taxonomy", "term"]

[services.disqus]
shortname = ""

[taxonomies] # This theme does not use "tag" and "category" taxonomies

[Params]
    tagline = "Florian Franzen"
    author = "Florian Franzen"
    description = "Architecture | Infrastructure | Research | Leadership"
    logoBig = "/images/effsquared.png"
    logoSmall = "/images/effsquared.png"
    favicon = true
    opengraphImage = "opengraph.png"
    github = "FlorianFranzen"
    bitbucket = "FlorianFranzen"
    linkedin = "FlorianFranzen"
    keybase = "FlorianFranzen"
    email = "mbjljrng"
    googleTagManger = ""
    highlightJS = true
    copyright = true
    credit = true
    customCSS = false
    cacheBustCSS = true
    cacheBustJS = true
    ajaxFormspree = true

[[menu.main]]
    name = "About"
    url  = "/#about"
    weight = 1
#[[menu.main]]
#    name = "Work"
#    url  = "/#work"
#    weight = 2
#[[menu.main]]
#    name = "Blog"
#    url  = "/#blog"
#    weight = 3
[[menu.main]]
    name = "Contact"
    url  = "/#contact"
    weight = 4
